// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using foll_backend.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace foll_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512013556_InitialCare")]
    partial class InitialCare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.EmergencyContact", b =>
                {
                    b.Property<long>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("emergency_contact_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EmergencyContactId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("relationship");

                    b.HasKey("EmergencyContactId")
                        .HasName("pk_emergency_contacts");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_emergency_contacts_patient_id");

                    b.ToTable("emergency_contacts", "care");
                });

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.Patient", b =>
                {
                    b.Property<long>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PatientId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<short>("BloodType")
                        .HasColumnType("smallint")
                        .HasColumnName("blood_type");

                    b.Property<long?>("CurrentGuardianUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_guardian_user_id");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("medical_conditions");

                    b.Property<long>("OfficialGuardianUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("official_guardian_user_id");

                    b.HasKey("PatientId")
                        .HasName("pk_patients");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_dni");

                    b.ToTable("patients", "care");
                });

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.PatientInvitation", b =>
                {
                    b.Property<long>("PatientInvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("patient_invitation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PatientInvitationId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<long>("InvitingUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("inviting_user_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<short>("RelationshipTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("relationship_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("PatientInvitationId")
                        .HasName("pk_patient_invitations");

                    b.HasIndex("InvitingUserId")
                        .HasDatabaseName("ix_patient_invitations_inviting_user_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_invitations_patient_id");

                    b.ToTable("patient_invitations", "care");
                });

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.RelationshipType", b =>
                {
                    b.Property<short>("RelationshipTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("relationship_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("RelationshipTypeId")
                        .HasName("pk_relationship_types");

                    b.ToTable("relationship_types", "care");

                    b.HasData(
                        new
                        {
                            RelationshipTypeId = (short)1,
                            Name = "Hijo"
                        },
                        new
                        {
                            RelationshipTypeId = (short)2,
                            Name = "Vecino"
                        },
                        new
                        {
                            RelationshipTypeId = (short)3,
                            Name = "Enfermera"
                        },
                        new
                        {
                            RelationshipTypeId = (short)4,
                            Name = "Familiar"
                        });
                });

            modelBuilder.Entity("foll_backend.IAM.Domain.Model.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "iam");
                });

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.EmergencyContact", b =>
                {
                    b.HasOne("foll_backend.Care.Domain.Model.Entities.Patient", null)
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_emergency_contacts_patients_patient_id");
                });

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.Patient", b =>
                {
                    b.OwnsMany("foll_backend.Care.Domain.Model.ValueObjects.CaregiverRole", "Caregivers", b1 =>
                        {
                            b1.Property<long>("patient_id")
                                .HasColumnType("bigint")
                                .HasColumnName("patient_id");

                            b1.Property<long>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("user_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("UserId"));

                            b1.Property<short>("RelationshipTypeId")
                                .HasColumnType("smallint")
                                .HasColumnName("relationship_type_id");

                            b1.HasKey("patient_id", "UserId")
                                .HasName("pk_user_patients");

                            b1.ToTable("user_patients", "care");

                            b1.WithOwner()
                                .HasForeignKey("patient_id")
                                .HasConstraintName("fk_user_patients_patients_patient_id");
                        });

                    b.Navigation("Caregivers");
                });

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.PatientInvitation", b =>
                {
                    b.HasOne("foll_backend.Care.Domain.Model.Entities.Patient", null)
                        .WithMany("Invitations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_invitations_patients_patient_id");
                });

            modelBuilder.Entity("foll_backend.Care.Domain.Model.Entities.Patient", b =>
                {
                    b.Navigation("EmergencyContacts");

                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
